apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"argo","app.kubernetes.io/name":"argo","kustomize.component":"argo"},"name":"argo-ui","namespace":"kubeflow"},"spec":{"gateways":["kubeflow-gateway"],"hosts":["*"],"http":[{"match":[{"uri":{"prefix":"/argo/"}}],"rewrite":{"uri":"/"},"route":[{"destination":{"host":"argo-ui.kubeflow.svc.cluster.local","port":{"number":80}}}]}]}}
  creationTimestamp: "2021-04-02T07:18:10Z"
  generation: 1
  labels:
    app.kubernetes.io/component: argo
    app.kubernetes.io/name: argo
    kustomize.component: argo
  name: argo-ui
  namespace: kubeflow
  resourceVersion: "21277676"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/kubeflow/virtualservices/argo-ui
  uid: 9a09491a-d81c-420e-b6fd-b76f5619d30f
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /argo/
    rewrite:
      uri: /
    route:
    - destination:
        host: argo-ui.kubeflow.svc.cluster.local
        port:
          number: 80
